bucket/vscode-insiders.json

vscode-insiders@1.57.0-insider: Fix hash

---

bucket/pester.json

Change the installation steps since they were based on an older version ( < 5 ).
No ticket
:unamused:

pester : Change the installation steps

---

assets/vscode-install-context.reg
assets/vscode-uninstall-context.reg

Add the windows registry file for VSCode in this bucket instead of using the one externally
Not related

Add vscode reg file in assets

---

bucket/vscode.json

For setting up the context menu, VSCode will now use the windows registry file from the assets folder of this repository
Not related

vscode: Change registry files assets location

---

bucket/vscode-insiders.json

VSCode-Insiders seems to use a "canary-build" version and new "file" replace the current version of file (for example 1.57.0-insider). Because of that, since the URL and version didn't changed the hashes wasn't updated by the "excavator Actions".
This "tweak" change finds the exact location of a version and will use it until the next version changes (minor, major or patch)
Also, we changed the registry files location to use this repository instead of an external
Not related
:disappointed:

vscode-insiders: Change to a static url and hashes

---

bucket/dotnet-sdk.json
bucket/mongodb.json
bucket/php.json
bucket/vcredist2012.json
bucket/vcredist2013.json
bucket/vcredist2019.json
bucket/windows-terminal.json
bucket/zoom.json

Some apps requires a version of "Visual C++ Redistributable". Versions that were able to work as "portable" were added (based on the ones existing in the "extras bucket" with the addition in the PATH.
Apps that had dependcy over them has also been updated.
Not related
:sweat:

vcredist: Add multiple portable version and update dependents

---

assets/vscode-install-context.reg

The VSCode regedit file to register the conext menu was inacurate
Not Related
:scream:

assets: Fix VSCode regedit file

---

bucket/vscode-insiders.json
bucket/vscode.json

Since the assets file for vscode has changed, the hashes used for them (vscode & vscode-insiders) has to be updated
Not Related
:scream::scream:

vscode+vscode-insiders: update assets file hashes

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/other_work.md

Update PR templates for app manifest (default one) and "other work". From the PR template, there is now an explanation on how to change the PR template. Reshuffling sections and optimizing/unifying the validations answers. And also added a new section about the type of change
The Contributing page has also been updated better explain how to contribute to the project
Not related
:sparkles:

Update PR templates and contributing doc

---

bucket/terraform-ls.json
bucket/terraform.json

Add the Terraform Langage Server (used in VSCode and other EDI).
Add a suggestion in terraform app to install the language server as well
Not related 
:bowtie:

terraform-ls: Add version 0.16.3

---

bucket/owasp-threatdragon.json

Add the OWASP Threat Dragon to help design threat model "as code"
Not related
:neckbeard: :innocent:

owasp-threatdragon: Add version 1.4.0

---

bucket/deepl.json

DeepL is a tools that can help translate text in differente language
The x86 version seems to be limited to 2.4.0, since its create some "automation" issue I removed it. It will require a modification if/when the x86 version issue of DeepL is resolved
Not related
:flushed:

deepl: Add version 2.5.0

---

bucket/winget-cli.json

WinGet CLI is the new windows DesktopAppInstaller that can be run in the command line. It can then install app that are not available to be deployed as "portable" and available and known from the winget source (also available as experimental is the MSStore source)
Not related
:dancer:

winget-cli: Add Version 1.0.11451

---

bucket/lens.json

Lens has a new way to release the executable. A couple of modifications has been done to make this work with the autoupdate and checkversion while updating to the current version
No
:pleading_face: :relieved:

lens: Update to version 5.2.2-latest.20210918.1

---

bucket/terraform-docs.json

Add cli to generate terraform documentation
None
:page_with_curl: :innocent:

terraform-docs: Add Version 0.15.0

---

bucket/dependency-check.json

Software composition analysis utility that identifies project dependencies and checks if there are any known, publicly disclosed, vulnerabilities.
none
:bug: :mag: :loudspeaker:

dependency-check: Add Version 6.4.1

---

bucket/zaproxy.json

Integrated penetration testing tool for finding vulnerabilities in web applications
none
:unlock: :smiling_imp: :dart: :feelsgood:

zaproxy: Add Version 2.11.0

---

.github/PULL_REQUEST_TEMPLATE.md

This is to update the PR template to include the exact command to launch when verifying the json/configuration of the app
none
:snowboarder:

Update the PR template to help the copy/paste of each commands to launch

---

bucket/vault.json

vault.exe ia a tool for secrets management, encryption as a service, and privileged access management
none
:closed_lock_with_key: :gun: :sob:

vault: Add Version 1.9.0

---

bucket/tflint.json

Terraform Lint
None
:crystal_ball:

tflint: Add Version 0.33.1

---

bucket/tfsec.json

Add Manifest for TFSec which ia a static analysis for terraform.
note : I had to fixed the version to 0.63.0 since the windows version is not available for the last 0.63.1... So in the manifest it's missing the autoupdate and checkversion section... Once it resolved we should re-add these sections
None
:mag: :bug: :punch: :wave: :rotating_light:

tfsec: Add Version 0.63.0

---

bucket/kube-linter.json

Add KubeLinter, a static analysis tool for k8s yaml files and helm charts
None
:tada:

kube-linter: Add Version 0.2.5

---

bucket/googlechrome.json

Fix the autoupdate for Google Chrome, which was no longer working from the previous uri. A new one has been publish with ScoopInstaller.
None
:alien: :bug: :bricks:

googlechrome: Fix autoupdate

---

bucket/lens.json

It fixes the url which uses spaces instead of its escaped character (%20)
None
:wrench: :bug:

lens: Fix url with escape characters

---

bucket/openssl-lts.json

I initially added a note on the manifest mentioning the fact that this version was for the long-term support version of openssl that was originally named `openssl-v1`. Before merging we renamed the manifest to a more suited and standardizes name of `openssl-lts` but I forgot to remove the note that was now irrelevant. This PR remove that now useless note.
:x: :notebook:

Update openssl-lts: Removed the obvious, and now inaccurate, note about version used

---

bucket/draw.io.json

Update draw.io manifest following some changes made by draw.io repo
None
https://gitmoji.dev/ => :alien: :zap: :sparkles: :recycle: :wheelchair: :adhesive_bandage:

draw.io: Update version 16.5.1 and add 32bit support and autorefresh

---

bucket/gimp.json

Update the autorefresh for Gimp and refactor the installation steps
None
https://gitmoji.dev/ => :zap: :sparkles: :recycle:

gimp: Update version 2.10.30 and fix installer + autorefresh

---

bucket/tfsec.json

tfsec has resolve its issue with the windows availability, so we added the autorefresh functionnality
None
https://gitmoji.dev/ => :alien: :zap: :sparkles: :recycle: :adhesive_bandage:

tfsec : Update version 1.0.2 and add autorefresh

---

bucket/oh-my-posh.json

Update the 'oh-my-posh' verison and fix the autoupdate after a change on the download url project.
None
:alien: :bug:

oh-my-posh: Update version 7.10.1 and Fix the autoupdate

---

bucket/grype.json

Add Grype to be able to scan for vulnerability within a Docker image
None
:sparkles: :tada: :monocle_face: :technologist: :cop:

grype: Add version 0.33.0

---

bucket/syft.json

Syft can export a Build of Material from an docker image and can be use to analyse vulenrability afterward
None
:sparkles: :tada: :monocle_face: :technologist: :cop: :floppy_disk: :books:

syft: Add version 0.38.0

---

.gitattributes

Fixes scoop sync issues where git corrupts images and marks them as modified
🐛🚸🩹🧑‍💻🔧

Fix git corrupting images

---

bucket/psyamlquery.json

PSYamlQuery leverage the yq.exe functionalities available in the main bucket
None
:tada: :sparkles: :technologist:

PSYamlQuery: Add version 1.0

---

bucket/dockle.json

Dockle is a cli that lint the security of a container image
None
:sparkles: :lock:

dockle: Add verion 0.4.5

---

bucket/aztfy.json

Azure Terrafy imports the resources that are supported by the [Terraform AzureRM provider](https://github.com/hashicorp/terraform-provider-azurerm) within a resource group, into the Terraform state, and generates the corresponding Terraform configuration.
none
:sparkles: :tada: :monocle_face: :bricks:

aztfy: Add version 0.1.1

---

bucket/daxstudio.json

DAX Studio is a tool to write, execute, and analyze DAX queries
None
:sparkles: :monocle_face: :alembic: :poop:

daxstudio: Add version 2.17.3

---

README.md

Remove the warning about git and propose steps to execute in PowerShell instead
:zap: :wrench: :page_facing_up: :children_crossing: :technologist:

Update README.md to remove warning and propose steps instead

---

bucket/adobe-digital-editions.json

Adobe Digital Editions can be use to read and sync ebooks (including borrowed one) to eReaders
None
:sparkles: :package: :page_facing_up:

adobe-digital-editions: Add version 4.5.11

---

bucket/sysinternals.json

sysinternals@2022.July.19: Fix hash

---

bucket/sysinternals.json

Bring sysinternals changes from Extras bucket

---

bucket/ant-renamer.json

Ant Renamer lets you manipulate file names in batch. Very useful when you need to rename lots of file in different places.
None
✨🚚

ant-renamer: Add Version 2.12.0

---

bucket/oh-my-posh.json

Update the manifest of Oh-My-Posh to fit the new licence, notes and versions (like the one from the main bucket).
None
:bug: :recycle:

oh-my-posh: Update manifest and version to 8.29.5

---

bucket/oh-my-posh.json

Update the manifest after changes in releases of oh-my-posh
None
:bug: :rotating_light: :recycle:

oh-my-posh: Update to version 12.6.7

---

bucket/owasp-threatdragon.json

owasp-threatdragon@1.4.0: Fix hash

---

bucket/python.json

Fix the Python manifest based on the changes done in the main bucket from scoop
Fixes #64 
:bug: :children_crossing: :alien: :poop: :angry:

python: Fix manifest file

---

bucket/oh-my-posh.json

The actions "Excavator" seems to have had and issue to update the 32bit hash... :anguished:
Issues : #67 
🚑️💩:alien:🚨

oh-my-posh: Update to version 12.11.0

---

bucket/postman.json

Postman do not support 32bits since v10
#67 ( well it seems the the Excavator experienced it too :confounded: )
:fire: :alien: :clown_face:

postman: Update to version 10.0.1

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/other_work.md

Move upward the emoji section in the PR template to be more easily viewable in the PR Tabs (without scrolling) :sweat_smile:
None
:lipstick: :wheelchair: :beers:

PR Templates : Moving up the gif/emoji section

---

bucket/dotnet-sdk.json

Change the manifest to be similar of the dotnet-sdk-sts version. Also adding the arm64 support. These change will add some feature to work side-by-side with the dotnet-sdk-sts version.
None
:technologist: :safety_vest: :wrench: :ambulance:

dotnet-sdk: Update the manifest to fit the dotnet-sdk-sts version

---

bucket/edgedriver.json

Update the edgedriver to the newest version, add arm64 support. Also, the response from the edgedriver LATEST_BETA is now in unicode, so we need to change how checkver is obtained
None, except the excavator wasn't able to obtain the new version
:alien: :bug: :package:

edgedriver: Update to version 108.0.1462.20 and fix checkver

---

.github/CODEOWNERS

Fix the codeowners name for the team to be able to activate the "auto add" reviewers on PR
None
:green_heart:  + maybe :alien: ??? (or me :sweat_smile:)

codeowners: fix the name :sweat_smile:

---

bucket/draw.io.json

We needed to update the draw.io release name to be able to update to the newest version
none
:alien: :bug: :wrench: :truck:

draw.io: Update to version 20.3.0

---

bucket/kube-linter.json

Update to the new release name for kube-linter
none
:unamused: :alien: :truck:

kube-linter: Update to version 0.5.0

---

assets/windows-terminal/install-context.reg
assets/windows-terminal/uninstall-context.reg

Add assets for the windows-terminal (which will be used by the refactoring in pr #78)
None
:bento: :building_construction: :twisted_rightwards_arrows:

assets: Add for windows-terminal

---

bucket/windows-terminal.json

Update to the new release name for windows-terminal and Refactor the manifest to be able to access WT from the context menu
none
:unamused: :alien: :truck: :boom:
:sparkles: :rocket: :necktie: :technologist:

windows-terminal: Update to version 1.15.2874.0

---

bucket/graphviz.json

Change the autoupdate url
None - only wasn't autoupdating within the workflow
:alien: :truck: :bug: :recycle:

graphviz: Update to version 7.0.1

---

bucket/obs-studio.json

Remove the OBS-Studio 32bits Url for the new version, which isn't available anymore
:alien: :truck: :bug: :unamused:

obs-studio: Update to version 28.1.2

---

bucket/inkscape.json

Inkscape seems to have changed and complexify how to obtain a file automatically. The checkver section now use a script (thank to the bucket extras :wink:)
None, only showed within the workflow
:alien: :truck: :bug:

inkscape: Update to version 1.2.1

---

bucket/sysinternals.json

sysinternals@2022.11.10: Fix hash

---

bucket/python.json

python@3.11.1: Fix hash

---

bucket/tabulareditor.json

Add TabularEditor tool. 
> Tabular Editor 2.x is a free, open-source, tool that lets you easily manipulate and manage measures, calculated columns, display folders, perspectives and translations in Analysis Services Tabular and Power BI XMLA Models (from Compatibility Level 1200 and onwards). The tool is written entirely in .NET WinForms (C#).
Thanks!

tabulareditor.json : Add version 2.17.3

---

bucket/sysinternals.json

sysinternals@2023.03.30: Fix hash

---

bucket/windows-terminal.json

The new version of the windows-terminal, which is now "portable"
No
:alien: :boom: :children_crossing: :sparkles:

windows-terminal: Update to version 1.17.11461.0

---

bucket/windows-terminal-1-16.json

This new manifest is the rename version of the windows-terminal to support the version 1.16 installation which is different of the new portable version available since the 1.17 version
No
:truck: :alien: :bookmark: :poop: :wastebasket: :pushpin:

windows-terminal-1-16: Add previous version 1.16.10261.0

---

bucket/python.json

python@3.11.5: Fix hash

---

bucket/vscode.json

It seems to create some issues with the certificat from update.code.visualstudio.com since the download occurs through a redirection on az764295.vo.msecnd.net ＼（〇_ｏ）／
I should've create one... well, next time maybe 
:clown_face:

vscode@1.82.3: Change download url

---

bucket/postman-10136.json

This is to keep the scratchpad version of postman
:bookmark: :alien: :poop:

Postman: Keep a version with scratchpad

---

bucket/vscode.json

Updating the manifest to remove the 32bits (no longer available) and adding the arm64 version. Because of that the auto-update from the excavator was failing.
Updating the manifest to add file associations and registering the context menu and file association on post_install
... one day I won't forget to create one ... 😅
⚡️🚀🚑️

vscode: Update to version 1.84.2

---

bucket/dotnet6-sdk.json

.NET6 sdk is still supported and some projects still requires its presence.
There is also an enhancement on how to get the version and hash that could be relevant in other dotnet manifests
None
🤦‍♂️ :recycle: :clown_face: :alembic:

dotnet6-sdk: Add version 6.0.417

---

bucket/dotnet-sdk-sts.json

Unifying the manifest file with other dotnet manifest for the autoupdate.hash and the checkver sections.
Updating to the latest version of the sdk-sts
None
:adhesive_bandage: :zap: :wrench:

dotnet-sdk-sts: Update to version 7.0.404 and update the manifest

---

bucket/vktablet-driver.json

This is the app and drivers for the Veikk Pen Tablet and Veikk Pen Display
none
:tada: :art: :rocket:

vktablet-driver: Add version 2.1.4.2

---

bucket/zoom.json

Updating to the latest version
Updating the manifest and use a new approach to grab the version
None
:alien: :zap: :wrench:

zoom: Update to 5.17.0.28375 and modify the manifest

---

README.md

The installation script given in the repository's README is not working properly.
N/A
📝🐛

Fix installation script

---

bucket/gitkraken.json

Manifest taken from scoop's _Extras_ bucket.
N/A
✨🔧

Add GitKraken manifest

---

bucket/inkscape.json

Inkscape seems to have changed how it distributes new versions. Extras' manifest has been recovered to fix the business bucket. 
#92 
🐛💚

Fix inkscape manifest

---

bucket/inkscape.json

Fix the extract_dir to use "inkscape" and change the version number the remove the date and commit hash
Fixes #116
🚑️🚨

inkscape: Fix extract_dir and change the version number

---

bucket/score-humanitec.json

Add score-humanitec manifest to enable installation from Scoop.
N/A
✨🔧

score-humanitec : Add version 0.10.0

---

bucket/score-helm.json

Add score-helm manifest to enable installation from Scoop.
N/A
✨🔧

score-helm: Add version 0.8.0

---

bucket/score-compose.json

Add score-compose manifest to enable installation from Scoop.
N/A
✨🔧

score-compose: Add version 0.8.0

---

bucket/humctl.json

Add humctl manifest to enable installation from Scoop.
N/A
✨🔧

humctl: Add version 0.13.3

---

bucket/picpick.json

Change the download URL to fit the new one
Fixes #122
👽 🐛

picpick: Update the download link

---

bucket/chromium.json

chromium@122.0.6261.56: Fix hash

---

bucket/vscode.json

Enforce to persist the users data within scoop instead of the "default" windows locations
None
:package: :truck: :lock: :safety_vest:

vscode: enforce persist data

---

bucket/databricks_cli.json

Add databricks command line tool. 
> The Databricks command-line interface (also known as the Databricks CLI) provides a tool to automate the Databricks platform from your terminal, command prompt, or automation scripts.
Thanks!

databricks_cli: Add version 0.215.0

---

bucket/terraform-ls.json

Fix the download urls of terraform-ls that were moved outside github
Fixes #127

terraform-ls: Update to version 0.32.7 and fix manifest

---

bucket/terraform-graph-beautifier.json

- Update the download url for 64bit which changed over the year
- Add arm64 support
Fixes #128
:alien::bug::lipstick:

terraform-graph-beautifier: Update to version 0.3.4 and add support for arm64

---

bucket/chromedriver.json

Update to version 122.0.6261.128. Fix the download url and add 64bit support 
Fixes #134
:alien::wastebasket::thread:

chromedriver: Update to version 122.0.6261.128 and fix the manifest

---

bucket/sqlite.json

- Fix the download url that support x64 now
- Update to latest version
Fixes #129
:alien: :wastebasket:

sqlite: Update to version 3.45.2

---

bucket/openssl.json

Update the manifest to make it similar as the main one since a lot of changes occured : https://github.com/ScoopInstaller/Main/blob/master/bucket/openssl.json
Fixes #132
:alien: :necktie:

openssl: Update to 3.2.1

---

bucket/nodejs-lts.json

- Fix the checkver regex to find the latest version
- Add support for arm64
Fixes #135
:alien: :bug: :sparkles: :bento:

nodejs-lts: Update to version 20.11.1

---

bucket/nodejs.json

Adding support for arm64 for NodeJS
None
:sparkles: :bento:

nodejs: Add support for arm64

---

bucket/kube-linter.json

- Update the download url
- Add support for arm64
Fixes #124
:bug: :sparkles: :bento:

kube-linter: Update to version 0.6.8

---

bucket/vncviewer.json

- Change the download url to fit with the new one
- Remove the hash autoupdate section since it don't seems to exists/work anymore
Fixes #133
:alien: :fire: :bug:

vncviewer: Update to version 7.10.0

---

bucket/scoop-completion.json

Updated the checkver url since the "releases" seem to have disappeared.
Fixes #93
🤷‍♂️

scoop-completion: Update to version 0.3.0

---

bucket/obs-studio.json

Update the checkver and the download url since the name changed
Fixes #125
:alien: :bug:

obs-studio: Update to version 30.1

---

bucket/xmind8.json

Fix the manifest since the domain domain name changed
Update the version to the real number
Fixes #94
:alien: 🛸

xmind8: Update to 3.7.9

---

bucket/python.json

Since it's no longer possible to do some regex directly on the content of the website in commandline easily , I propose to revert back to the github repos and use the tag instead. The tags seems to be accurate enough.
With an issue similar with the autoupdate hash, I removed it and enforce that all downloaded files must be autoupdated and not only the python exe.
Fixes #158
:alien: :lock: :poop:

Python: Fix checkver and autoupdate

---

bucket/dotnet-sdk-sts.json

Update to latest version and fix the checkver
None
🐛

dotnet-sdk-sts: Update to version 9.0.100-preview.3.24204.13 and fix the checkver

---

bucket/dotnet-sdk.json

Update to latest version and fix the checkver
None
🐛

dotnet-sdk: Update to version 8.0.204 and fix the checkver

---

bucket/chromium.json

chromium@124.0.6367.90: Fix hash

---

bucket/7zip.json

- Change the 7zip installation process since some enterprise are limiting or blocking some msi installation 😒
- Also Fix a little issue with the checkvers which included the beta version.
None, but someone should have created an issue for that  🤣
👔💩🐛

7zip: Downgrade to version 23.01 (official version)

---

bucket/dotnet6-sdk.json

dotnet6-sdk@6.0.423: Fix hash

---

bucket/vlc.json

vlc@3.0.21: Fix hash

---

bucket/chromium.json

chromium@127.0.6533.76: Fix hash

---

bucket/dotnet-sdk.json

Update dotnet-sdk to latest version and remove the regex which seems to fail
N/A
:egg: or :bug: => :see_no_evil:

dotnet-sdk: Update to version 8.0.303

---

bucket/azure-cli.json

Update azure-cli to latest version and use the zip file instead
N/A
:egg: or :bug: => :see_no_evil:

azure-cli: Update to version 2.62.0 and use zip file instead

---

bucket/dotnet-sdk-sts.json

Update dotnet-sdk-sts to latest preview version and remove the regex which seems to fail
N/A
:egg: or :bug: => :see_no_evil:

dotnet-sdk-sts: Update to version 9.0.100-preview.6.24328.19

---

bucket/obs-studio.json

Update the checkver configuration and update to the latest version
None
:pencil2: :alien: :wrench:

obs-studio: Update to version 30.2.2

---

bucket/nodejs-lts.json

Change the checkver configurations and update to the latest version
None
:pencil2: :safety_vest:

nodejs-lts: Update to version 2.16.0

---

bucket/devtoys.json

DevToys App : A Swiss Army knife for developers.
None
:sparkles: :package: :beers: :technologist:

devtoys: Add version 2.0.5.0

---

bucket/devtoys-cli.json

DevToys CLI : A Swiss Army CLI knife for developers.
None
:sparkles: :package: :beers: :technologist:

devtoys-cli: Add version 2.0.5.0

---

bucket/vscode.json

vscode@1.96.2: Fix hash

---

bucket/snyk-cli.json

Add the Snyk CLI that help scans and monitors your projects for security vulnerabilities
None, only that I now need that tool 😋
:stethoscope: your :poop: for :passport_control: and :safety_vest: your :package: and the :necktie:

snyk-cli: Add version 1.1295.2

---

bucket/go.json

Change the depractated functions and add arm64
None
YOLO! :)

go: Remove deprecated pwsh functions and add arm64

---

bucket/python.json

Fix an issue with the script folder
None
:bug: :dizzy:

python: Persist the Scripts folder

---

bucket/dotnet-sdk.json

Revert to version 8.0.406 since the new .NET10 preview release
None
:bug: :poop: :see_no_evil:

dotnet-sdk: Revert to version 8.0.406

---

bucket/dotnet-sdk-preview.json

Add the new LTS-Preview version for dotnet
None
:tada: :clown_face: :sparkles:

dotnet-sdk-preview: Add version 10.0.100-preview.1.25120.13

---

bucket/vscode.json

vscode@1.98.1: Fix hash

---

bucket/vscode-insiders.json

Fix an issue on how the checkversion extracted the timestamp
None
:bug: :see_no_evil:

vscode-insiders: Update to version 1.99.0-1741621990865 and fix checkver

---

bucket/vscode.json

vscode@1.99.2: Fix hash

---

assets/opera-gx/install-context.reg
bucket/opera-gx.json

Update to the version 120.0.5543.127, adjust registry entries and improve the manifest
None
:green_heart: :wrench: :bento:

opera-gx: Update to version 120.0.5543.127

---

bucket/vscode.json

vscode@1.103.0: Fix hash

---

bucket/zoom.json

A file name changed in the installer that needed to be change to fix the install/update process
None
:alien: :ambulance:

zoom@6.5.7.9933: Fix pre_install

---

bucket/vscode.json

vscode@1.103.1: Fix hash
